title = "Reguna"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

enableRobotsTXT = true

enableEmoji = true

pluralizelisttitles = false

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
author = "Eric Leung"
info = "Aspiring Full Stack Developer"
description = "Eric Leung's personal website"
keywords = "blog,developer,personal"
avatarurl = "https://github.com/regunakyle.png"
images = ["https://github.com/regunakyle.png"]

faviconSVG = "favicon.svg"
favicon_32 = "favicon-32x32.png"
favicon_16 = "favicon-16x16.png"
touchIcon = "apple-touch-icon.png"

since = 2023

colorScheme = "dark"
hidecolorschemetoggle = true

customCSS = ["detail.css"]

[params.giscus] # https://giscus.app
repo = "regunakyle/regunakyle"
repoID = "R_kgDOJKgcVA"
category = "Giscus"
categoryID = "DIC_kwDOJKgcVM4Cmp3c"
mapping = "og:title"
term = ""
strict = "1"
reactionsEnabled = "0"
emitMetadata = "0"
inputPosition = "top"
theme = "preferred_color_scheme"
lang = "en"
loading = "lazy"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-2x fa-brands fa-github"
weight = 10
url = "https://github.com/regunakyle"
[[params.social]]
name = "Discord"
icon = "fa-2x fa-brands fa-discord"
weight = 20
url = "https://discordapp.com/users/263243377821089792"
[[params.social]]
name = "Email"
icon = "fa-2x fa-solid fa-envelope"
weight = 30
url = "mailto:contact@ericleung.dev"
[[params.social]]
name = "RSS"
icon = "fa-2x fa-solid fa-square-rss"
weight = 30
url = "./posts/index.xml"

# Menu links
[[menu.main]]
name = "About"
weight = 10
url = "about"
[[menu.main]]
name = "Blog"
weight = 20
url = "posts/"
[[menu.main]]
name = "Projects"
weight = 40
url = "projects"
