title = "Reguna"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

enableRobotsTXT = true

paginate = 20

enableEmoji = true

pluralizelisttitles = false

[services]
[services.googleAnalytics]
ID = 'G-7G8KK1FRKB'

[markup.highlight]
style = "github-dark"

[params]
author = "Eric Leung"
info = "Aspiring Full Stack Developer"
description = "Eric Leung's personal website"
keywords = "blog,developer,personal"
avatarurl = "https://github.com/regunakyle.png"

favicon_32 = "favicon-32x32.png"
favicon_16 = "favicon-16x16.png"
touchIcon = "apple-touch-icon.png"

since = 2023

colorScheme = "dark"
hidecolorschemetoggle = true

customCSS = ["detail.css"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-2x fa-brands fa-github"
weight = 10
url = "https://github.com/regunakyle"
[[params.social]]
name = "Discord"
icon = "fa-2x fa-brands fa-discord"
weight = 20
url = "https://discordapp.com/users/263243377821089792"
[[params.social]]
name = "Telegram"
icon = "fa-2x fa-brands fa-telegram"
weight = 30
url = "https://t.me/regunakyle"
[[params.social]]
name = "RSS"
icon = "fa-2x fa-solid fa-square-rss"
weight = 30
url = "./posts/index.xml"

# Menu links
[[menu.main]]
name = "About"
weight = 10
url = "about"
[[menu.main]]
name = "Blog"
weight = 20
url = "posts/"
[[menu.main]]
name = "Projects"
weight = 40
url = "projects"
